export class OkHiFields {
    static billingPhoneField = '#billing_phone';
    static billingLastNameField = '#billing_last_name';
    static billingFirstNameField = '#billing_first_name';
    static requiredAddressField = '#billing_address_1';
    static billingPostcodeField = '#billing_postcode';
    static billingOtherInformationField = '#order_comments';
    static billingStreetNameField = '#billing_okhi_street_name';
    static billingPropertyNameField = '#billing_okhi_property_name';
    static billingPropertyNumberField = '#billing_okhi_property_number';
    static billingOkHiLatField = '#billing_okhi_lat';
    static billingOkHiLonField = '#billing_okhi_lon';
    static billingOkHiPlaceIdField = '#billing_okhi_place_id';
    static billingOkHiIdField = '#billing_okhi_id';
    static billingOkHiTokenField = '#billing_okhi_token';
    static billingOkHiURLField = '#billing_okhi_url';
    static locationCardContainerElement = '#selected-location-card';
    static errorElement = '#okhi-errors';
}
